### ISSUE TITLE
Hello World Requirement.

### ISSUE THREAD

**Issue by heyfirst** [alchemist-itbangmod/helloworld-ask#1]
Create an React application (Gatsby.js) that can send questions to store in Database (MariaDB) via API Server (ExpressJS)

### Task:
- [ ] Create AskComponent for enter the question text and send it to API
- [ ] Create ExpressJS for get request data and store it to Database
- [ ] Create AdminComponent for retrieve questions from the Database and show them on the browsers
- [ ] **Optional** try to use MobX to manage state data
- [ ] **Optional** try to use Socket.io to make real-time AdminComponent

### Note
you can see the [ASK Repository](https://github.com/alchemist-itbangmod/) to reference for developing this task.

**Comment by trrekiiz** [comment]
โหดจัง
